import { Player } from './models/player';
import { Position } from './enums/position.enum';

export const PLAYERS: Player[] = [
  {
    id: 1,
    firstName: 'Cristiano',
    lastName: 'Ronaldo',
    position: Position.Striker,
    currentClub: 'Al-Nassr',
    dateOfBirth: '05.02.1985',
    height: '1.87 m',
    nationality: 'Portugal',
  },
  {
    id: 2,
    firstName: 'Lionel',
    lastName: 'Messi',
    position: Position.Striker,
    currentClub: 'Inter Miami CF',
    dateOfBirth: '24.06.1987',
    height: '1.70 m',
    nationality: 'Argentina',
  },
  {
    id: 3,
    firstName: 'Sergio',
    lastName: 'Ramos',
    position: Position.Defender,
    currentClub: 'Sevilla FC',
    dateOfBirth: '30.03.1986',
    height: '1.84 m',
    nationality: 'Spain',
  },
  {
    id: 4,
    firstName: 'Kylian',
    lastName: 'Mbappe',
    position: Position.Striker,
    currentClub: 'Paris Saint-Germain',
    dateOfBirth: '20.12.1998',
    height: '1.78 m',
    nationality: 'France',
  },
  {
    id: 5,
    firstName: 'Antonio',
    lastName: 'Rüdiger',
    position: Position.Defender,
    currentClub: 'Real Madryt',
    dateOfBirth: '03.03.1993',
    height: '1.90 m',
    nationality: 'Germany',
  },
  {
    id: 6,
    firstName: 'Jude',
    lastName: 'Bellingham',
    position: Position.Midfielder,
    currentClub: 'Real Madryt',
    dateOfBirth: '29.06.2003',
    height: '1.86 m',
    nationality: 'England',
  },
  {
    id: 7,
    firstName: 'Luka',
    lastName: 'Modrić',
    position: Position.Midfielder,
    currentClub: 'Real Madryt',
    dateOfBirth: '09.09.1985',
    height: '1.72 m',
    nationality: 'Croatia',
  },
  {
    id: 8,
    firstName: 'Toni',
    lastName: 'Kroos ',
    position: Position.Midfielder,
    currentClub: 'Real Madryt',
    dateOfBirth: '04.01.1990',
    height: '1.83 m',
    nationality: 'Germany',
  },
  {
    id: 9,
    firstName: 'Robert',
    lastName: 'Lewandowski',
    position: Position.Striker,
    currentClub: 'FC Barcelona',
    dateOfBirth: '21.08.1988',
    height: '1.85 m',
    nationality: 'Poland',
  },
  {
    id: 10,
    firstName: 'Kevin',
    lastName: 'De Bruyne',
    position: Position.Midfielder,
    currentClub: 'Manchester City F.C.',
    dateOfBirth: '28.06.1991',
    height: '1.81 m',
    nationality: 'Belgium',
  },
  {
    id: 11,
    firstName: 'Bernardo',
    lastName: 'Silva',
    position: Position.Midfielder,
    currentClub: 'Manchester City F.C.',
    dateOfBirth: '10.08.1994',
    height: '1.73 m',
    nationality: 'Portugal',
  },
  {
    id: 12,
    firstName: 'Dani',
    lastName: 'Carvajal',
    position: Position.Defender,
    currentClub: 'Real Madryt',
    dateOfBirth: '11.01.1992',
    height: '1.73 m',
    nationality: 'Spain ',
  },
  {
    id: 13,
    firstName: 'Éder',
    lastName: 'Militão',
    position: Position.Defender,
    currentClub: 'Real Madryt',
    dateOfBirth: '18.01.1998',
    height: '1.86 m',
    nationality: 'Brazil',
  },
  {
    id: 14,
    firstName: 'Manuel',
    lastName: 'Neuer ',
    position: Position.Goalkeeper,
    currentClub: 'Bayern Monachium',
    dateOfBirth: '27.03.1986',
    height: '1.93 m',
    nationality: 'Germany',
  },
  {
    id: 15,
    firstName: 'Thibaut',
    lastName: 'Courtois',
    position: Position.Goalkeeper,
    currentClub: 'Real Madryt',
    dateOfBirth: '11.05.1992',
    height: '2.00 m',
    nationality: 'Belgium',
  },
];
